# SPDX-License-Identifier: GPL-2.0-only
CFLAGS += -Wall -O2 -Wno-unused-function
CFLAGS += $(KHDR_INCLUDES)

CFLAGS += -D_GNU_SOURCE

TEST_GEN_PROGS := qemu_edu_test qemu_edu_test_v2

include ../lib.mk
